// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ElevationSystem.h"
#include "../Robotmap.h"
ElevationSystem::ElevationSystem() : Subsystem("ElevationSystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	elevationController = RobotMap::elevationSystemElevationController;
	upLimit = RobotMap::elevationSystemUpLimit;
	downLimit = RobotMap::elevationSystemDownLimit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ElevationSystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void ElevationSystem::Up(){
	elevationController->Set(.5);
}
void ElevationSystem::Down(){
	elevationController->Set(-.5);
}
void ElevationSystem::Stop(){
	elevationController->Set(0);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
